- name: Remove unwanted packages
  dnf:
    name: '{{ packages }}'
    state: absent
    autoremove: yes
  vars:
    packages:
      - PackageKit
      - gnome-software
      - fedora-chromium-config

- name: Upgrade all packages
  dnf:
    name: '*'
    state: latest

- name: Enable the RPM Fusion repository
  dnf:
    name:
      - 'https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm'
      - 'https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm'
    state: present
    disable_gpg_check: yes

- name: Install packages
  package:
    name: '{{ packages }}'
    state: present
  vars:
    packages:
      # dev
      - git
      - git-filter-repo
      - java-11-openjdk-devel
      - java-11-openjdk-src
      - nodejs
      - yarnpkg
      - python3-peewee
      - gcc
      - gcc-c++
      - clang
      - valgrind
      - gtk4-devel
      - make
      - ffmpeg
      - ImageMagick
      # rust
      - rust
      - rust-src
      - cargo
      - rls
      - rustfmt
      # tex
      - texlive
      - latexmk
      - texlive-chktex
      - texlive-latexindent
      - texlive-wrapfig
      - texlive-sourcesanspro
      - texlive-fontawesome
      - texlive-tcolorbox
      - texlive-clrscode3e
      - texlive-tikz-qtree
      - texlive-upquote
      - texlive-ifoddpage
      - texlive-acmart
      # apps
      - celluloid
      - code
      - epiphany
      - evolution
      - evolution-ews
      - gimp
      - gimp-dds-plugin
      - htop
      - google-chrome-stable
      - inkscape
      - nautilus-python
      - neovim
      - seahorse
      - seahorse-nautilus
      - sqlitebrowser
      - vlc
